### ISSUE TITLE
Error first configuration

### ISSUE THREAD

**Issue by stefanoferrario** [paoloantinori/ha_vodafone_power_station_device_tracker#6]
Hi

after first configuration I have this error in my log

Error setting up platform legacy vodafone_power_station

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 248, in async_setup_legacy
    scanner = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/vodafone_power_station/device_tracker.py", line 34, in get_scanner
    scanner = VodafonePowerStationDeviceScanner(config[DOMAIN])
  File "/config/custom_components/vodafone_power_station/device_tracker.py", line 52, in __init__
    data = self.get_router_data()
  File "/config/custom_components/vodafone_power_station/device_tracker.py", line 152, in get_router_data
    _LOGGER.debug("Full Response: %s" % response.json())
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by paoloantinori** [comment]
I'm no longer using this components but the error: 

`Expecting value: line 1 column 1 (char 0)`

suggest the remote call has received an empty payload. Are you certain you have provided the correct ip/hostname and that it is reacheable from you HA instance?

**Comment by chemelli74** [comment]
@stefanoferrario, please join HomeAssistant  on [Discord](https://discord.com/invite/home-assistant) and then contact me: `chemelli74#2180`

Simone
