### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dirtydurkin101** [paoloantinori/ha_vodafone_power_station_device_tracker#7]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 282, in async_setup_legacy
    scanner = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/vodafone_power_station/device_tracker.py", line 34, in get_scanner
    scanner = VodafonePowerStationDeviceScanner(config[DOMAIN])
  File "/config/custom_components/vodafone_power_station/device_tracker.py", line 52, in __init__
    data = self.get_router_data()
  File "/config/custom_components/vodafone_power_station/device_tracker.py", line 107, in get_router_data
    csrf = m.group(0)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by chemelli74** [comment]
@dirtydurkin101, working on a new library, your help would be much appreciated

Please join HomeAssistant  on [Discord](https://discord.com/invite/home-assistant) and then contact me: `chemelli74#2180`

Simone
