### ISSUE TITLE
Error setting up platform legacy vodafone_power_station

### ISSUE THREAD

**Issue by simonegirlanda** [paoloantinori/ha_vodafone_power_station_device_tracker#8]
Since a few weeks I'm having this error and the device tracker is no more working.

can I help to solve?

Logger: homeassistant.components.device_tracker
Source: custom_components/vodafone_power_station/device_tracker.py:154
Integration: Device tracker (documentation, issues)
First occurred: 09:34:57 (1 occurrences)
Last logged: 09:34:57

Error setting up platform legacy vodafone_power_station
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 293, in async_setup_legacy
    scanner = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/vodafone_power_station/device_tracker.py", line 34, in get_scanner
    scanner = VodafonePowerStationDeviceScanner(config[DOMAIN])
  File "/config/custom_components/vodafone_power_station/device_tracker.py", line 52, in __init__
    data = self.get_router_data()
  File "/config/custom_components/vodafone_power_station/device_tracker.py", line 154, in get_router_data
    _LOGGER.debug("Full Response: %s" % response.json())
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Amerigo1973** [comment]
the same for me

**Comment by chemelli74** [comment]
Working on a new integration that will be part of the core.

Can you share the exact model of Vodafone Station you are using ?

If you want to contact me on discord we can test the new library together.

Simone

**Comment by Amerigo1973** [comment]
Il mer 12 lug 2023, 13:32 Simone Chemelli ***@***.***> ha
scritto:

**Comment by asettico** [comment]
Nome del prodotto: Vodafone Power Station
Versione e tipo hardware: VOX30v1
Versione Firmware: XS_3.9.00.05

let me know how can I contribute.

**Comment by chemelli74** [comment]
> Nome del prodotto: Vodafone Power Station Versione e tipo hardware: VOX30v1 Versione Firmware: XS_3.9.00.05

Thx!
 
> let me know how can I contribute.

Please join HomeAssistant  on [Discord](https://discord.com/invite/home-assistant) and then contact me: `chemelli74#2180`

Simone
